name: Deploy Zodiaq App to Azure Web App

on:
  push:
    branches:
      - zodiaq

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login with Service Principal
        uses: azure/login@v2
        with:
          creds: '{"clientId": "5e0345b8-e505-4a7e-bdba-570ce3117f5f", "clientSecret": "YY_8Q~V3KNU5.jw_XsouG2AS_tikzhtKHdQ0ibum", "subscriptionId": "6ed18a24-80e3-4abe-99a6-ee3286ec36e6", "tenantId": "ab2cd235-acf4-4759-a7e3-dd97a44dba3a"}'
          enable-AzPSSession: true

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Azure Subscription
        run: |
          az account set --subscription 6ed18a24-80e3-4abe-99a6-ee3286ec36e6

      - name: Get Commit ID (first 5 characters)
        id: get_commit_id
        run: |
          COMMIT_ID=${GITHUB_SHA:0:5}
          echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t zodiaq:${{ env.COMMIT_ID }} -f Dockerfile .

      - name: Login to Azure Container Registry
        run: |
          docker login zodiaq.azurecr.io -u zodiaq -p yqJMc4B55eTNfBWtMvPVRBMIV+AlHXu0HiKwM8NVxy+ACRDR9vMM

      - name: Tag Docker Image
        run: |
          docker tag zodiaq:${{ env.COMMIT_ID }} zodiaq.azurecr.io/zodiaq:${{ env.COMMIT_ID }}

      - name: Push Docker Image to ACR
        run: |
          docker push zodiaq.azurecr.io/zodiaq:${{ env.COMMIT_ID }}

      - name: Set Web App Port
        run: |
          az webapp config appsettings set --resource-group flowgic --name zodiaqapp --settings WEBSITES_PORT=8080

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --resource-group flowgic \
            --name zodiaqapp \
            --docker-custom-image-name zodiaq.azurecr.io/zodiaq:${{ env.COMMIT_ID }}
